version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: campus-events-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - campus-events-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: campus-events-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/campus-events
      - PORT=5000
    depends_on:
      - mongo
    networks:
      - campus-events-network
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: campus-events-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - campus-events-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:5000

networks:
  campus-events-network:
    driver: bridge

volumes:
  mongo-data: